ReportDefinitions:
- reportName: DescriptionReport
  decryptionPathId: DescriptionReport
  summary: Fetches the Ticket details
  version: 1.0.0
  moduleName: Incident
  sourceColumns:
  - name: incidentid
    label: Ticket No.
    type: string
    source: eg_incident_v2
    total: false
  - name: incidenttype
    label: Ticket Type
    type: string
    source: eg_incident_v2
    total: false
  - name: incidentsubtype
    label: Ticket Sub Type
    type: string
    source: eg_incident_v2
    total: false
  - name: applicationstatus
    label: Status
    type: string
    source: eg_incident_v2
    total: false
  searchParams:
   - name: name
    label: Ticket Sub Type
    type: singlevaluelist
    source: eg_incident_v2
    pattern: http://egov-mdms-service:8080/egov-mdms-service/v1/_get?tenantId=$tenantid&moduleName=Incident&masterName=ServiceDefs|$.MdmsRes.Incident.ServiceDefs[*].code|$.MdmsRes.incident.ServiceDefs[*].name
    isMandatory: false
    searchClause: AND im.incidentsubtype = $name
  - name: fromDate
    label: From Date
    type: epoch
    source: eg_incident_v2
    isMandatory: true
    searchClause: AND im.createdtime >= $fromDate
  - name: toDate
    label: To Date
    type: epoch
    source: eg_incident_v2
    isMandatory: true
    searchClause: AND im.createdtime <= $toDate
  query: |
        select im.incidentid,im.incidenttype,im.incidentsubtype,im.tenantid,im.applicationstatus, im.district,im.block from eg_incident_v2 im where 1=1

- reportName: RegionalStatusofIncident
  summary: This report provides the details of status of Incidents.
  version: 1.0.0
  moduleName: pgr
  externalService:
  - entity: $.MdmsRes.RAINMAKER-PGR.ServiceDefs
    apiURL: http://egov-mdms-service:8080/egov-mdms-service/v1/_get?moduleName=RAINMAKER-PGR&masterName=ServiceDefs&tenantId=$tenantId
    keyOrder: serviceCode,name
    tableName: tbl_dept
  sourceColumns:
  - name: name
    label: Incident Type
    type: string
    source: eg_pgr_service
    total: false
  - name: new
    label: New Incidents 
    type: number
    source: eg_pgr_service
    total: true
  - name: assigned
    label: Assigned Incidents 
    type: number
    source: eg_pgr_service
    total: true
  - name: reassigned
    label: Reassigned Incidents 
    type: number
    source: eg_pgr_service
    total: true
  - name: reopened
    label: Reopened Incidents 
    type: number
    source: eg_pgr_service
    total: true
  - name: rejected
    label: Rejected Incidents 
    type: number
    source: eg_pgr_service
    total: true
  - name: resolved
    label: Resolved Incidents 
    type: number
    source: eg_pgr_service
    total: true
  - name: rated
    label: Completed with Citizen Rating
    type: number
    source: eg_pgr_service
    total: true
  searchParams:
  - name: locality
    label: reports.pt.locality
    type: singlevaluelist
    pattern: http://egov-location.egov:8080/egov-location/location/v11/boundarys/_search?hierarchyTypeCode=ADMIN&boundaryType=Locality&tenantId=$tenantid|$.TenantBoundary[0].boundary.*.code|$.TenantBoundary[0].boundary.*.code
    source: pt
    wrapper: true
    isMandatory: false
    localisationPrefix: TENANTS_MOHALLA_
    isLocalisationRequired: true
    searchClause: AND pad.locality = $locality 
  - name: fromDate
    label: From Date
    type: epoch
    source: eg_pgr_service
    isMandatory: true
    searchClause: AND la.createdtime >= $fromDate
  - name: toDate
    label: To Date
    type: epoch
    source: eg_pgr_service
    isMandatory: true
    searchClause: AND la.createdtime <= $toDate
  - name: name
    label: Incident Type
    type: singlevaluelist
    source: eg_pgr_service
    pattern: http://egov-mdms-service:8080/egov-mdms-service/v1/_get?tenantId=$tenantid&moduleName=RAINMAKER-PGR&masterName=ServiceDefs|$.MdmsRes.RAINMAKER-PGR.ServiceDefs[*].name|$.MdmsRes.RAINMAKER-PGR.ServiceDefs[*].name   
    isMandatory: false
    searchClause: AND departmap.name = $name
  query: |
    WITH latest_actions AS(SELECT ad.id,ad.servicerequestid,ad.servicecode,aoa.action,aoa.createdtime FROM eg_pgr_service_v2 ad 
    JOIN eg_wf_processinstance_v2 aoa ON ad.servicerequestid = aoa.businessid
    WHERE aoa.action NOT IN('COMMENT') and
    aoa.createdtime = (
        SELECT
            MAX(createdtime)
        FROM
            eg_wf_processinstance_v2
        WHERE
            businessid = ad.servicerequestid
    ))
    SELECT  departmap.name,
       SUM(CASE WHEN la.action = 'APPLY' THEN 1 ELSE 0 END) AS NEW,
       SUM(CASE WHEN la.action = 'ASSIGN' OR la.action = 'ASSIGNEDBYAUTOESCALATION' THEN 1 ELSE 0 END) AS ASSIGNED,
       SUM(CASE WHEN la.action = 'REASSIGN' THEN 1 ELSE 0 END) AS REASSIGNED,
       SUM(CASE WHEN la.action = 'REOPEN' THEN 1 ELSE 0 END) AS REOPENED,
       SUM(CASE WHEN la.action = 'REJECT' OR la.action ='CANCEL'  THEN 1 ELSE 0 END) AS REJECTED,
       SUM(CASE WHEN la.action = 'RESOLVEBYSUPERVISOR' OR la.action = 'RESOLVE' THEN 1 ELSE 0 END) AS RESOLVED,
       SUM(CASE WHEN la.action = 'RATE' THEN 1 ELSE 0 END) AS Rated
       FROM latest_actions la JOIN eg_pgr_address_v2 pad on la.id=pad.parentid INNER JOIN (VALUES tbl_dept) AS departmap(serviceCode, name) 
    ON departmap.serviceCode = la.servicecode WHERE 1=1
  groupby: GROUP BY departmap.name

- reportName: GlobalStatusofIncident
  summary: This report provides the details of status of incidents.
  version: 1.0.0
  moduleName: pgr
  externalService:
  - entity: $.MdmsRes.RAINMAKER-PGR.ServiceDefs
    apiURL: http://egov-mdms-service:8080/egov-mdms-service/v1/_get?moduleName=RAINMAKER-PGR&masterName=ServiceDefs&tenantId=$tenantId
    keyOrder: serviceCode,name
    tableName: tbl_dept
  sourceColumns:
  - name: name
    label: Incident Type
    type: string
    source: eg_pgr_service
    total: false
  - name: new
    label: New Incidents 
    type: number
    source: eg_pgr_service
    total: true
  - name: assigned
    label: Assigned Incidents 
    type: number
    source: eg_pgr_service
    total: true
  - name: reassigned
    label: Reassigned Incidents 
    type: number
    source: eg_pgr_service
    total: true
  - name: reopened
    label: Reopened Incidents 
    type: number
    source: eg_pgr_service
    total: true
  - name: rejected
    label: Rejected Incidents 
    type: number
    source: eg_pgr_service
    total: true
  - name: resolved
    label: Resolved Incidents 
    type: number
    source: eg_pgr_service
    total: true
  - name: rated
    label: Completed with Citizen Rating
    type: number
    source: eg_pgr_service
    total: true
  searchParams:
  - name: country
    label: Country
    type: singlevaluelist
    pattern: http://egov-mdms-service:8080/egov-mdms-service/v1/_get?tenantId=$tenantid&moduleName=tenant&masterName=tenants|$.MdmsRes.tenant.tenants.*.code|$.MdmsRes.tenant.tenants.*.name
    source: tl
    wrapper: true
    isMandatory: false
    searchClause: AND pad.tenantId = $country
  - name: fromDate
    label: From Date
    type: epoch
    source: eg_pgr_service
    isMandatory: true
    searchClause: AND la.createdtime >= $fromDate
  - name: toDate
    label: To Date
    type: epoch
    source: eg_pgr_service
    isMandatory: true
    searchClause: AND la.createdtime <= $toDate
  - name: name
    label: Incident Type
    type: singlevaluelist
    source: eg_pgr_service
    pattern: http://egov-mdms-service:8080/egov-mdms-service/v1/_get?tenantId=$tenantid&moduleName=RAINMAKER-PGR&masterName=ServiceDefs|$.MdmsRes.RAINMAKER-PGR.ServiceDefs[*].name|$.MdmsRes.RAINMAKER-PGR.ServiceDefs[*].name   
    isMandatory: false
    searchClause: AND departmap.name = $name
  query: |
    WITH latest_actions AS(SELECT ad.id,ad.servicerequestid,ad.servicecode,aoa.action,aoa.createdtime FROM eg_pgr_service_v2 ad 
    JOIN eg_wf_processinstance_v2 aoa ON ad.servicerequestid = aoa.businessid
    WHERE aoa.action NOT IN('COMMENT') and
    aoa.createdtime = (
        SELECT
            MAX(createdtime)
        FROM
            eg_wf_processinstance_v2
        WHERE
            businessid = ad.servicerequestid
    ))
    SELECT  departmap.name,
       SUM(CASE WHEN la.action = 'APPLY' THEN 1 ELSE 0 END) AS NEW,
       SUM(CASE WHEN la.action = 'ASSIGN' OR la.action = 'ASSIGNEDBYAUTOESCALATION' THEN 1 ELSE 0 END) AS ASSIGNED,
       SUM(CASE WHEN la.action = 'REASSIGN' THEN 1 ELSE 0 END) AS REASSIGNED,
       SUM(CASE WHEN la.action = 'REOPEN' THEN 1 ELSE 0 END) AS REOPENED,
       SUM(CASE WHEN la.action = 'REJECT' OR la.action ='CANCEL'  THEN 1 ELSE 0 END) AS REJECTED,
       SUM(CASE WHEN la.action = 'RESOLVEBYSUPERVISOR' OR la.action = 'RESOLVE' THEN 1 ELSE 0 END) AS RESOLVED,
       SUM(CASE WHEN la.action = 'RATE' THEN 1 ELSE 0 END) AS Rated
       FROM latest_actions la JOIN eg_pgr_address_v2 pad on la.id=pad.parentid INNER JOIN (VALUES tbl_dept) AS departmap(serviceCode, name) 
    ON departmap.serviceCode = la.servicecode WHERE 1=1
  groupby: GROUP BY departmap.name